sudo: required
language: elixir
elixir:
  - 1.6.0
otp_release:
  - 19.0
cache: apt
env:
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
before_install:
  - curl -fsSkL https://gist.githubusercontent.com/tonini/74a12bfd4f99e872385de6ea0bc39700/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  - cask --debug
install:
  - cask install
script:
  - emacs --version
  - make
notifications:
  irc: "irc.freenode.org#emacs-elixir"
